<?php

function movie_reservation_controller_theme($existing,$type,$theme,$path){
    
    return [
        'article_list' => [
            'variables' => ['items' => [], 'title' => '']
        ],
        'data_list' => [
            'variables' => ['items' => [], 'title' => '']
        ],
        'export_list' => [
            'variables' => ['items' => [], 'title' => '']
        ],
        'reservation_list' => [
            'variables' => ['items' => [], 'title' => '']
        ]
    ];
}