<?php

function movie_reservation_controller_theme($existing,$type,$theme,$path){
    
    return [
        'article_list' => array(
            'variables' => array('items' => array(), 'title' => '')
        ),
        'data_list' => array(
            'variables' => array('items' => array(), 'title' => '')
        ),
        'export_list' => array(
            'variables' => array('items' => array(), 'title' => '')
        ),
        'reservation_list' => array(
            'variables' => array('items' => array(), 'title' => '')
        )
    ];
}